/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteReservationsRouteImport } from './routes/_site.reservations'
import { Route as SiteMenuRouteImport } from './routes/_site.menu'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReservationsRoute = SiteReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMenuRoute = SiteMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/menu': typeof SiteMenuRoute
  '/reservations': typeof SiteReservationsRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof SiteAboutRoute
  '/menu': typeof SiteMenuRoute
  '/reservations': typeof SiteReservationsRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/menu': typeof SiteMenuRoute
  '/_site/reservations': typeof SiteReservationsRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/about' | '/menu' | '/reservations'
  fileRoutesByTo: FileRoutesByTo
  to: '/sitemap.xml' | '/about' | '/menu' | '/reservations' | '/'
  id:
    | '__root__'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/about'
    | '/_site/menu'
    | '/_site/reservations'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reservations': {
      id: '/_site/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof SiteReservationsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/menu': {
      id: '/_site/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof SiteMenuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteMenuRoute: typeof SiteMenuRoute
  SiteReservationsRoute: typeof SiteReservationsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteMenuRoute: SiteMenuRoute,
  SiteReservationsRoute: SiteReservationsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
