/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml";
import { Route as SiteRouteImport } from "./routes/_site";
import { Route as SiteIndexRouteImport } from "./routes/_site.index";
import { Route as SiteReservationsRouteImport } from "./routes/_site.reservations";
import { Route as SiteMenuRouteImport } from "./routes/_site.menu";
import { Route as SiteAboutRouteImport } from "./routes/_site.about";

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
});
const SiteRoute = SiteRouteImport.update({
  id: "/_site",
  getParentRoute: () => rootRouteImport,
});
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SiteRoute,
});
const SiteReservationsRoute = SiteReservationsRouteImport.update({
  id: "/reservations",
  path: "/reservations",
  getParentRoute: () => SiteRoute,
});
const SiteMenuRoute = SiteMenuRouteImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => SiteRoute,
});
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => SiteRoute,
});

const SiteRouteChildren = {
  SiteAboutRoute,
  SiteMenuRoute,
  SiteReservationsRoute,
  SiteIndexRoute,
};

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren);

const rootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute,
};

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);
